### ISSUE TITLE
Integrate storage API with data capture

### ISSUE THREAD

**Issue by biancadanforth** [electrolyfish/lightbeam-we#42]
Update `capture.js` to call `store.setFirstParty` and `store.setThirdParty` methods.
Use consistent naming between arguments in `capture.js` and method parameters in `store.js`.

Questions to answer:
- What is the difference between `origin`, `target`, and `document` URLs?
- How often are `origin` URLs different from `document` URLs?
- What to do in these cases?

```javascript
// from capture.js  
async sendThirdParty(response) {
    const tab = await browser.tabs.get(response.tabId);
    const documentUrl = new URL(tab.url);
    const targetUrl = new URL(response.url);
    const originUrl = new URL(response.originUrl);

    if (targetUrl.hostname !== documentUrl.hostname) {
      const thirdPartyData = {
        document: documentUrl.hostname,
        target: targetUrl.hostname,
        origin: originUrl.hostname,
        requestTime: response.timeStamp
      };
      store.setThirdParty(documentUrl.hostname, targetUrl.hostname, thirdPartyData);
    }
  }
```

**Comment by biancadanforth** [comment]
**What is the difference between origin, target, and document URLs?**
`origin`:
- [documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onResponseStarted#details)
- string. URL of the resource that triggered this request. Note that this may not be the same as the URL of the page into which the requested resource will be loaded. For example, if a document triggers a load in a different window through the target attribute of a link, or a CSS document includes an image using the url() functional notation, then this will be the URL of the original document or of the CSS document, respectively.
- Note: In the webRequest web extension API for the onResponseStarted method (what is used in `capture.js`), this is derived from the details.originUrl property.

`target`:
- [documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onResponseStarted#details)
- The target resource URL requested by the originUrl.
- Note: In the webRequest web extension API for the onResponseStarted method (what is used in `capture.js`), this is derived from the details.url property.

`document`:
- [documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/get)
- string. The URL of the document that the tab is displaying. This is the URL in the tab’s address bar for the website the user has visited.
- Note: In the tabs webextension API for the get method (what is used in `capture.js`), this is derived from the tab.url value.

**How often are origin URLs different from document URLs?**
I created a counter for the number of third party requests (TPRs) that had an originUrl differ from its documentUrl and visited several websites to get an idea:
- Youtube.com: 28/113 TPRs
- Fastcompany.com 21/223 TPRs
- Hulu.com: 3/117 TPRs
- Medium.com: 0/118 TPRs

**What to do in these cases?**
My guess: nothing. @jonathanKingston, Please weigh in!
My thinking: While the `origin` URL may differ from the `document` URL, the request is still being made as a result of the user visiting the site at `document` URL, albeit indirectly. Therefore, we would not care if the `origin` URL differs from the `document` URL. We would only be interested in when the `document` URL differs from the `target` URL, which we are already using as the condition to identify a third party request.

**Comment by jonathanKingston** [comment]
> We would only be interested in when the document URL differs from the target URL

I think this is correct yeah.

Firefox also has the undocumented [`response.documentUrl`](http://searchfox.org/mozilla-central/source/toolkit/components/extensions/ext-webRequest.js#53) it might be worth checking how different that is to `tab.url`. My hunch is that this will provide iframe URLs that loaded the `target` rather than saving us querying for the tab, it also likely will differ from `origin` as it won't encapsulate CSS loading other CSS file for example. As it's undocumented I might be not understanding it correctly though.

Things to consider:
- My hunch is you will mostly find `parentFrameId`to not be -1 when `origin` is not `document`
- Consider filtering requests that are in tabId -1. I don't think we will see it often for what we are doing.
- What about third parties are requesting the first party.
  - For example some tracking scripts might expect the developer to install some client side scripts also. (lets make this a stretch though unless you think you want this)

User visits mozilla.com
- `document` is `mozilla.com`
- `target` is `mozilla.com/user.js`
- `origin` is `evil.com`

This looks great work and I agree with your synopsis. Worst case scenario we can always change the logic after more testing anyway.

**Comment by biancadanforth** [comment]
Thanks @jonathanKingston .

I am looking at `response.documentUrl`, but it is returning `undefined` every time for my `onResponseStarted` requests... What response object or event is that property present in? I am reluctant to use undocumented properties in general -- isn't that risky?

In response to your _Things to consider_:
 - You are correct that when `origin` differs from `document`, `parentFrameId` is another integer, 0, not -1. This means there is a parent frame for that request. I'm guessing that parent frame is the `document`? What is the significance here of that?
- Aren't I already filtering for `tabId` of -1 with this [condition](https://github.com/biancadanforth/lightbeam-we/commit/f3ba4121abe6d6fca5be79842c30b19b76573549#diff-11bef26aa0da2e103508b47252406a5fR46):
`tabId !== browser.tabs.TAB_ID_NONE`?
- What do you mean by: "What about third parties are requesting the first party." Are you suggesting there are instances where third parties are requesting first-party resources like client-side scripts? Why might they want to do that, and how is it possible for third-parties to be making requests from a first-party site?

**Comment by jonathanKingston** [comment]
> I am reluctant to use undocumented properties in general -- isn't that risky?

I already spoke to web extension devs about it, it's not documented because I think it might not be in stable. Also no, I was just making a point it exists. We are likely to want Chrome support at some point so using this is likely not a great idea.

> What is the significance here of that?
Mostly none, just thought it would help explain what is happening here.

> Aren't I already filtering for tabId of -1

I think it might still happen for the webRequest third party code too.

> how is it possible for third-parties to be making requests from a first-party site?

Third party scripts can load a first party as if it were a third party script.

a.com/blah.js -> b.com/tracking-spam.js -> a.com/thing.js

My hunch is the current code won't account for this.

**Comment by biancadanforth** [comment]
> Third party scripts can load a first party as if it were a third party script.
> a.com/blah.js -> b.com/tracking-spam.js -> a.com/thing.js

@jonathanKingston No it wouldn't make a separate call to the storage API as written. But, if we are making a directed force graph, then a link between the first and third party would already be represented on the graph, wouldn't it? Should I make a separate issue for discussion of this?

**Comment by jonathanKingston** [comment]
Yeah follow up bug is fine, indeed it won't be represented on the current
graph. It's not MVP either.
