### ISSUE TITLE
Storage api is populated with old values

### ISSUE THREAD

**Issue by princiya** [electrolyfish/lightbeam-we#54]
STR:

- Open Lightbeam
- Open console
- Clear the storage manually through the console: `browser.storage.local.remove('websites').then(()=>console.log('removed')).catch(err=>console.log(err))`
- Also set `store._websites=null` manually through the console
- Refresh the page - graph disappears
- Refresh the page again, graph appears with old values

This shouldn't be the case. We need to ensure there is only once instance of `store`.

**Comment by jonathanKingston** [comment]
Unfortunately this is happening because there are more than one instance of store.js which is likely going to end in disaster.

The solution here is likely another object that messages to background version of store.js using message passing: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#Communicating_with_background_scripts

So one solution might look like:
```javascript
// store.js
const store = {
  async init() {
    const publicMethods = ["getAll"];
    browser.runtime.onMessage(responseHandler);
  },
  async responseHandler(m) => {
      if (publicMethods.includes(m.method)) {
        return this[m.method](...m.arguments);
      }
  },
  async getAll() {
    ...
  }
}
```

```javascript
// store-child.js
const storeChild = {
  getAll() {
    return await this.parentMessage("getAll", ...arguments);
  },
  parentMessage(method, ...arguments) {
    return browser.runtime.sendMessage({
      method,
      arguments
    })
  }
};
```

There might be something more elegant to make the code more DRY. Also naming might be something that can be improved, child/parent is used for processes within Firefox from content scripts to chrome level processes. However it's not really the same here.

The lightbeam page will use storeChild.js which will speak the the background script, the response from sendMessage is passed back as a promise, it should emulate the code pretty well as if it has the same instance.

**Comment by princiya** [comment]
@jonathanKingston Thanks for the detailed explanation here :) Working on this now. I am glad we figured this disastrous thing during our initial stages!!!!!

**Comment by jonathanKingston** [comment]
@princiya https://rosettacode.org/wiki/Respond_to_an_unknown_method_call#JavaScript can be used by the "store-child" to always call the parent and reduce overhead of having code in two places.
